# Generated by Django 3.2.13 on 2022-06-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Клиент',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=250, verbose_name='Клиент')),
                ('organization', models.CharField(max_length=250, verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Организации',
                'ordering': ['id'],
                'unique_together': {('organization', 'client_name')},
            },
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_client', models.CharField(max_length=250, verbose_name='Организация')),
                ('account_number', models.IntegerField(verbose_name='Номер счета')),
                ('balance', models.IntegerField(verbose_name='Баланс')),
                ('date', models.CharField(max_length=250, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Счета',
                'ordering': ['id'],
                'unique_together': {('organization_client', 'account_number')},
            },
        ),
    ]
