# Generated by Django 3.2.13 on 2022-06-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_org', models.CharField(max_length=250, verbose_name='Организация')),
                ('number', models.IntegerField(verbose_name='Номер счета')),
                ('bale', models.IntegerField(verbose_name='Баланс')),
                ('dat', models.DateField()),
            ],
            options={
                'verbose_name': 'Счета',
                'ordering': ['id'],
                'unique_together': {('client_org', 'number')},
            },
        ),
    ]
